### ISSUE TITLE
Search comes back as None

### ISSUE THREAD

**Issue by KBodolai** [Heladio-ac/python-ecosia-images#13] opened 2021-06-03 10:31 UTC
Hi. 

I was trying to use the library, and the following happened:

``` >>> from ecosia_images import crawler
>>> searcher=crawler()
>>> searcher.search('cerrado')
>>> searcher.links
{None}
>>> searcher.search('trees')
>>> searcher.links
{None}
 ```

Independently of what search term I add, no links come back. Anyone else experienced this? Any ideas on how to fix it?

Cheers,
K.

**Comment by Heladio-ac** [comment] 2021-06-04 19:59
Hi!

The `search` method triggers an update of the crawler, which gathers all links on the results page searching for elements with the HTML class `image-result`. However, It seems that the Ecosia images results page has changed since this library was created, now the links are contained in elements with the HTML class `image-result__details-link`.

The library could still work just as intended if this extract of the code in the ecosia_search.py file was corrected to accommodate for this change:

``` python
class crawler():
    ...
    def __update(self):
        """ Updates the images set with all the results on the page
        """
        elements = []
        try:
            elements = self.driver.find_elements_by_class_name('image-result')
            self.links |= set(map(extract_href, elements))
        except Exception as e:
            raise TimeoutError("No more images found")
        finally:
            if not len(elements):
                raise TimeoutError("Search did not return images")
```

I'll be sure to check it, make sure it works, and update the pip package in a few days. Also, if you'd like to correct it and upload the changes I'll gladly merge the changes!

Cheers

**Comment by KBodolai** [comment] 2021-06-04 20:12
Sure, thanks for this. I'll give it a whirl during the weekend, test it and make a PR. 

K.

**Comment by KBodolai** [comment] 2021-06-05 10:45
Alright. Managed to get some results changing  `image-result` for `image-result__link` (`image-result__details-link` redirects you to the original page instead of the image itself).

Another issue I've found is that results are consistently coming back with 24 links. When I use the crawler's `gather_more()` method, it'll time out, see error message below. All points out that it has something to do with the 'scrolling down' of selenium (this also happened before I fixed the first issue) unfortunately I'm not sure about how to fix that. What do you think?

```
Traceback (most recent call last):
  File "/Users/kbodolai/python-ecosia-images/ecosia_images/ecosia_search.py", line 153, in gather_more
    wait.until(EC.presence_of_element_located(css_selector))
  File "/Users/kbodolai/opt/anaconda3/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kbodolai/python-ecosia-images/ecosia_images/ecosia_search.py", line 155, in gather_more
    raise TimeoutError("No more images found")
TimeoutError: No more images found
```

**Comment by Heladio-ac** [comment] 2021-06-06 23:22
Great! just merged those changes.

Yes, currently the `gather_more` first scrolls down then waits for a loading animation to appear and disappear:

~~~ python
    def gather_more(self):
        ...    
        try:
            # wait for loading element to appear
            css_selector = (By.CSS_SELECTOR, "div.loading-animation")
            wait = WebDriverWait(self.driver, self.timeout)
            wait.until(EC.presence_of_element_located(css_selector))
        except TimeoutException:
            raise TimeoutError("No more images found")

        try:
            # then wait for the element to disappear from the viewport
            wait.until_not(element_in_viewport)
        except TimeoutException:
            raise TimeoutError("Lost internet connection")
~~~

However, checking the current design of ecosia the HTML loading element still exists but changed its class name to `loading__container`. Maybe it is just a matter of changing the CSS_SELECTOR to div.loading__container.

**Comment by KBodolai** [comment] 2021-06-07 08:12
Great, working on it.

Changing the css selector works.  Only a small quirk where the first `.gather_more()` call doesn't add anything, but subsequent calls do:

```
>>> searcher.search('soya plantation')
s>>>len(searcher.links))
24
>>> searcher.gather_more()
>>> len(searcher.links)
24
>>> searcher.gather_more()
>>> len(searcher.links)
80
>>> searcher.gather_more()
>>> len(searcher.links)
126
>>> searcher.gather_more()
>>> len(searcher.links)
176
```

I'm  trying to figure out if I can get around it, and will make another PR soon.

**Comment by KBodolai** [comment] 2021-06-09 09:18
Hi Heladio,

I was looking into the `.gather_more()` issue, but the `search()` methods is starting to act up again. I checked and the class name is still supposed to be `'image-result__link'`, however, no elements are returned and it jumps straight to TimeoutError, rendering our previous fix unusable, any ideas?

```
>>> from ecosia_images import crawler
>>> searcher = crawler()
>>> searcher.search('boats')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kbodolai/python-ecosia-images/ecosia_images/ecosia_search.py", line 137, in search
    self.__update()
  File "/Users/kbodolai/python-ecosia-images/ecosia_images/ecosia_search.py", line 177, in __update
    raise TimeoutError("Search did not return images")
TimeoutError: Search did not return images 
```

**Comment by KBodolai** [comment] 2021-06-16 14:01
Managed to pin down the issue to the chrome driver, it's working as expected with firefox's geckodriver. Will make a PR shortly with the fix for scrolling.

**Comment by Heladio-ac** [comment] 2021-06-18 23:48
Great! Sorry for the late response. Just merged the changes and will update the PyPi package shortly. Thanks for the updates!

**Closed by Heladio-ac** 2021-06-18 23:48 UTC
